FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY cliente_websocket_analysis.py ./

CMD ["python", "cliente_websocket_analysis.py"]
